### ISSUE TITLE
BRW5 to BR4 conversion

### ISSUE THREAD

**Issue by b-grimaud** [MicroBrew09/xenon-lfp-analysis#1]
Hello,

My team and I would be very interested in using this tool, not only for its main app but also for the additional modules.

In particular, I would like to be able to convert files in the BrainWave 5 file format (i.e. the multiwell compatible format) back to the BrainWave 4 format. It seems that the `ExportToHDF5-ChannelSelection.py` module is capable of this. 

However, I tried running the module while selecting all channels and setting the downsample at the original sampling rate, and the only results is a ~30 kB file that only contains a partially complete `3BRecInfo` dataset.

```
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> f = h5py.File('CxHipp4AP_01_exportCh.brw','r')
>>> f.keys()
<KeysViewHDF5 ['3BRecInfo']>
>>> f['3BRecInfo'].keys()
<KeysViewHDF5 ['3BMeaStreams', '3BRecVars']>
```

While looking through the `3Brian-processing` folder, I was a bit confused to find different `writeBrw` classes between each module, `ExportToHDF5-ChannelSelection`, `ExportToHDF5-ExtractDownsample` (which seems to rely on 3Brain DLLs), and `HD-MEA-DownSample`.

I also had to modify a few lines of the original `ExportToHDF5-ChannelSelection` module, as the path handling was Windows-specific.
Using `pathlib` makes the module work on both Linux and MacOS systems, as well as being easier to read, e.g. : 
```
Input_file_path = path0['Filename']
input_file_name = Input_file_path.split('\\')[-1]
input_file_path = '\\'.join(Input_file_path.split('\\')[0:-1])

output_file_name = input_file_name.split('.')[0]+"_exportCh"
output_file_name_brw = input_file_name.split('.')[0]+"_exportCh"+".brw"
output_path = input_file_path+'\\'+output_file_name_brw
```
becomes
```
from pathlib import Path
Input_file_path = Path(path0['Filename'])
input_file_name = Input_file_path.name
input_file_path = Input_file_path.parent

output_file_name = Input_file_path.stem+"_exportCh"
output_file_name_brw = Input_file_path.stem+"_exportCh"+".brw"
output_path = input_file_path.joinpath(output_file_name_brw)
```

**Comment by MicroBrew09** [comment]
Thank you @BptGrm for the path handling suggestion.

Yes, that is correct ExportToHDF5-ChannelSelection.py module generates an info file, with the '_exportCh.brw' extension. This is just a metadata file in hdf5 format with *.brw extension. 

After this file in generated, you can run 'ExportToHDF5-ExtractDownsample.py' to extract the channels you selected at the sampling rate selected. While using this on *.brw4 files, the module can write using hdf5 file format, and does not need the *.ddl files. You can comment out: 'from _3Brian*' imports, if required. 

However, as you may have noted for *.brw5 files, this needs the BrainWave5 software and their proprietary *.dll files to  uncompressing, extracting channels and write to hdf5 (brw4 format). This is quite slow, it runs once channel at a time, and it can take a long time if you have 4096 channels, and high sampling rate. 

If you have BrainWave5 software installed you can find the installation folder and give it the path, mostly this will only run on Windows. BrainWave5 software I believe is Windows specific, I am not sure if they have released a version for mac/linux.

clr.AddReference(os.path.join("C:\\Program Files\\3Brain\\BrainWave 5", "3Brain.BrainWave.IO.dll"))

Let me know if this works..

**Comment by b-grimaud** [comment]
Thanks a lot !
We tried it on a .brw4 file and it worked as expected.
Just a few notes : 
 - Specifying a file path in `ChannelSelection` does nothing until an image is uploaded as well. We routinely take photos of our slices on the chip, but they're not always at hand. I then have to upload random screenshots so that the file would load. Having a simple "Ok" or "Upload button" to the side would be convenient. Similarly, having a browsing prompt when selecting the .brw file, just like it is to select an image, might be a bit more intuitive than copy-pasting the file path itself. I apologize for not having concrete code suggestions, as I am not familiar with `Dash`.
 - `ExtractDownsample` has a strict Python 3.7 requirement, but `ChannelSelection` doesn't.
 Having `assert (sys.version_info[0],sys.version_info[1]) == (3, 7), "Please install/setup Python environment: Version-3.7"` at the top of `ChannelSelection` as well might save some time if they're always supposed to be used together.
 - Some channel coordinates seem to be swapped in the main LFP analysis window. The tuple displayed in both the channel selection widget and the raster plot match, but it is reversed in the `Select a Channel to View Trace` dropdown list. The latter seems to be the "correct" order e.g. I have a noisy channel in my recording, it is listed as (29,55) in both the channel selection widget and raster plot, but as (55,29) in the dropdown list. When I open that file in BrainWave, (55,29) is noisy but (29,55) isn't.

On a more general note regarding the overall pipeline shown in your paper : is there a reason why data is acquired at 10 kHz even though it is systematically downsampled afterwards ? The larger files can be difficult to handle, and downsampling seems to be time consuming even with .brw4 recordings.

**Comment by MicroBrew09** [comment]
Glad it worked! Thank you for the notes. 

- Yes, this is a work around if you don't have a picture. The problem with Dash is it is a stateless application, and the browser masks the local full file path. The upload/browse button loads the entire contents of the file (or just gets the filename) to memory and for some large hdf5 files this sometimes crashes the application or take a long time. 
- This is a valid point, I can add this. I also hope the BrainWave .dll files, will be updated to work with Python3.10, I ran into problems in late 2021, but it may have changed now.
-   Yes, this is a known issue, I don't have a way to easily correct it. The BrainWave channel mapping on the hdf5 file: row and column labels are reversed, the grid/raster is matched to the rows (y) and columns (x) (they are switched).  

The MEA system and BrainWave software (BW4), could not record below 10kHz, there was no option to record at a lower frequency, 10kHz was the lowest acquisition frequency. They may have updated BW5 to record at lower frequencies now, but it was not possible earlier. The file format and compression make it hard to process the data faster, it is indeed time consuming and slow.
