### ISSUE TITLE
Usage of HDF5 file

### ISSUE THREAD

**Issue by olesnits** [MicroBrew09/xenon-lfp-analysis#2]
Hello,

I am interested in using your software, but my recording was done on different MEA (not by [BrainWave Software - 3Brain])
So, I have HDF5 file extention format to upload into the software, which is not possible using GUI. However I wonder is there a way to do that modifying [Xenon-LFP-Analysis.py] code?

I would appreciate your feedback.
Best,
Olesia

**Comment by MicroBrew09** [comment]
Hi Olesia,

Yes, you can modify the Xenon-LFP-Analysis.py code, the current code is mapped to the BrainWave/3Brain MEA channel mapping and hdf5. You can use the same framework, and modify how the channels are read, and processed inside each Plotly-Dash callback function, is your sensor in row-column grid?
