### ISSUE TITLE
get_RecordingDuration issue in "ExtractDownsample" 

### ISSUE THREAD

**Issue by chloemhall** [MicroBrew09/xenon-lfp-analysis#3]
Hi there! 
I have raw recordings, in BW5, and am tripping up on the "ExportToHDF5- ExtractDownsample.py" stage. Traceback highlights line 437 - get_RecordingDuration as having no attribute... has this part been deleted from the code? Any pointers here would be great please. 

Also I wanted to say that in BW5 the Analog to Digital conversion formula has been altered... I might be wrong, but I believe your code still uses a voltage conversion with bitdepth for BW5. 
Here's the new:
 AnalogValue = MinAnalogValue + DigitalValue * (MaxAnalogValue – MinAnalogValue) / (MaxDigitalValue – MinDigitalValue)

Just in case. 

Thanks!

**Comment by MicroBrew09** [comment]
Hi, 
I think the new version of BW5 may have changed this attribute, it must be replaced by ‘.get_TimeDuration()’. Can you try and let me know.
I will check the Analog conversion. Thanks for letting me know.

**Comment by chloemhall** [comment]
Hi! That did indeed solve the problem. 
Many thanks.
